version: "3"

# This file is only there for developer convenience
# and should not be used for deployments.

x-nuxt: &nuxt
  build:
    context: ./
    dockerfile: ./Dockerfile
    args:
      TARGET: ${TARGET}
  command: start:${TARGET}

services:
  api:
    <<: *nuxt
