version: "3"

# This file is only there for developer convenience,
# it is not used in testing or deployments

x-nuxt: &nuxt
  build:
    context: ./
    dockerfile: ./Dockerfile
    args:
      TARGET: ${TARGET}
  command: start:${TARGET}

services:
  api:
    <<: *nuxt
