version: "3"

tasks:
  # Development & CI

  run:
    cmds:
      - nuxt dev

  test:
    cmds:

  format:prettier:
    cmds:
      - prettier --write .

  format:
    cmds:
      - task: format:prettier

  lint:prettier:
    cmds:
      - prettier --check .

  lint:eslint:
    cmds:
      - eslint . --fix

  lint:typescript:
    cmds:
      - vue-tsc

  lint:
    cmds:
      - task: lint:prettier
      - task: lint:eslint
      - task: lint:typescript

  # Docker

  build:testing:precopy:
    cmds:
      - npm install --include=dev

  build:testing:postcopy:
    cmds:
      - nuxt build

  build:deployment:precopy:
    cmds:
      - npm install

  build:deployment:postcopy:
    cmds:
      - nuxt build

  start:testing:
    cmds:
      - task: lint
      - task: test

  start:deployment:
    cmds:
      - node .output/server/index.mjs

  # Convenience

  install:taskfile:
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
