version: "3"

tasks:
  # Development & CI

  run:
    cmds:
      - nuxt dev

  test:
    cmds:

  format:xo:
    cmds:
      - xo --fix --prettier

  format:
    cmds:
      - task: format:xo

  lint:xo:
    cmds:
      - xo

  lint:
    cmds:
      - task: lint:xo

  # Docker

  build:testing:
    cmds:
      - npm install --include=dev
      - nuxt build

  build:deployment:precopy:
    cmds:
      - npm install

  build:deployment:postcopy:
    cmds:
      - nuxt build

  start:testing:
    cmds:
      - task: lint
      - task: test

  start:deployment:
    cmds:
      - node .output/server/index.mjs

  # Convenience

  install:taskfile:
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
