name: Deployment

on:
  push:
    branches:
      - master

env:
  DEPLOYMENT_TAG: 42juododranoel/textflowrhyme-frontend:latest

jobs:
  testing:
    uses: 42juododranoel/textflowrhyme-frontend/.github/workflows/testing.yml@master

  build:
    needs: [testing]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.DEPLOYMENT_TAG }}
          build-args: |
            TARGET=deployment

  deployment:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: 42juododranoel
          repo: textflowrhyme-infrastructure
          github_token: ${{ secrets._GITHUB_PAT }}
          workflow_file_name: deployment.yml
          ref: master
