name: Deployment

on:
  push:
    branches:
      - master

env:
  DEPLOYMENT_TAG: 42juododranoel/textflowrhyme-frontend:latest

jobs:
  testing:
    uses: 42juododranoel/textflowrhyme-frontend/.github/workflows/testing.yml@master

  build:
    runs-on: ubuntu-latest
    needs: [testing]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.DEPLOYMENT_TAG }}
          build-args: |
            TARGET=deployment

  deployment:
    uses: 42juododranoel/textflowrhyme-infrastructure/.github/workflows/deployment.yml@master
