name: Testing

on:
  push:
    branches-ignore:
      - master
  workflow_call:

env:
  TESTING_TAG: 42juododranoel/textflowrhyme-frontend:testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TESTING_TAG }}
          build-args: |
            TARGET=testing

      - name: Lint & Test
        run: |
          docker run --rm ${{ env.TESTING_TAG }} start:testing      
